dataset: "N2C" # 適当でいいらしいね.

path:
  source_raw_path: "./raw_data/N2C/nishimura"
  source_prevoice_path: "./pre_voice/N2C/nishimura"
  target_raw_path: "./raw_data/N2C/cherry"
  target_prevoice_path: "./pre_voice/N2C/cherry"
  preprocessed_path: "./preprocessed_data/N2C"  # out_dir. こっちはsource, targetで自動で分ける.

preprocessing:
  val_size: 20 # 元は512
  audio:
    sampling_rate: 24000
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    normalization: True
  energy:
    normalization: True