path:
  ckpt_path: "./output/ckpt/N2C"
  log_path: "./output/log/N2C"
optimizer:
  batch_size: 8  # default: 32
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  reset_optim: True
  init_lr: 1  # 最初のlearning rateにinit_lr倍します.
step:
  total_step: 120000  # default: 900000
  log_step: 50  # default: 100
  synth_step: 500  # default: 1000
  val_step: 500  # default: 1000
  save_step: 1500  # default: 10000
